---
AWSTemplateFormatVersion: '2010-09-09'
Description: Defines the serverless-video-pipeline micro-service resources (must be merged with sam.json)
Parameters:
  Environment:
    Type: String
    Description: Environment name (select from allowed values)
    AllowedValues:
    - prod
    - stage
    - dev

Resources:
  Transcoder:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: transcoder.yml
      Parameters:
        Environment: !Ref Environment

  StateMachine:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: state-machine.yml
      Parameters:
        Environment: !Ref Environment
        TranscoderPipelineId: !GetAtt Transcoder.Outputs.TranscoderPipelineId

  ApiExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: !Sub ${Environment}-ApiExecutionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetBucketLocation
            Resource:
            - !Sub arn:aws:s3:::${Transcoder.Outputs.TranscoderBucket}
          - Effect: Allow
            Action:
            - s3:PutObject
            Resource:
            - !Sub arn:aws:s3:::${Transcoder.Outputs.TranscoderBucket}/*
          - Effect: Allow
            Action:
            - states:StartExecution
            Resource:
            - !GetAtt StateMachine.Outputs.TranscoderStateMachineArn
          - Effect: Allow
            Action:
            - states:DescribeExecution
            Resource:
            - !Sub ${StateMachine.Outputs.TranscoderStateMachineExecutionBaseArn}*
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  TranscoderBucket:
    Value: !GetAtt Transcoder.Outputs.TranscoderBucket
